Repository go-vela/vela-docker, pull requests merged in 2021-04, with the labels that each got.

#23 fix(registry): skip validating user/pass with dry_run enabled
  cmd/vela-docker/registry.go
  cmd/vela-docker/registry_test.go
Labels: bug

#25 fix: setting daemon configuration with flag
  cmd/vela-docker/main.go
Labels: bug

#24 fix(registry): skip login with dry_run enabled
  cmd/vela-docker/registry.go
  cmd/vela-docker/registry_test.go
Labels: bug

#26 feat(daemon): enable tuning log level
  DOCS.md
  cmd/vela-docker/daemon.go
  cmd/vela-docker/daemon_test.go
Labels: feature

#27 enhance: fixed version output and optimized output order
  cmd/vela-docker/daemon.go
  cmd/vela-docker/plugin.go
Labels: enhancement

#28 fix: update docker-test and docker-run env var list
  Makefile
Labels: bug

#29 enhance: update filepaths and add DOCKER_ env vars
  DOCS.md
  cmd/vela-docker/build.go
  cmd/vela-docker/daemon.go
  cmd/vela-docker/push.go
  cmd/vela-docker/registry.go
Labels: enhancement

#30 feat: add Docker repository (repo) parameter
  DOCS.md
  cmd/vela-docker/build.go
  cmd/vela-docker/build_test.go
  cmd/vela-docker/main.go
Labels: feature

#31 chore: update parameters and samples in docs
  DOCS.md
Labels: enhancement

#32 fix: add json field tags to daemon
  cmd/vela-docker/daemon.go
Labels: bug
